POST http://localhost:5000/api/usuarios/login
Content-Type: application/json

{
"identificador": "44444444",
"contrasena": "12345"
}

POST http://localhost:5000/api/usuarios/registro
Content-Type: application/json

{
"nombre": "admi5",
"apellido": "control",
"correo": "admi5@ucr",
"telefono": "55555555",
"contrasena": "12345"
}
